"""add_correction_injection_fields

Revision ID: 68a27ba16b03
Revises: 9fe59c52a683
Create Date: 2026-03-01 23:19:15.941234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a27ba16b03'
down_revision: Union[str, Sequence[str], None] = '9fe59c52a683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corrections', sa.Column('domain', sa.String(length=100), nullable=False))
    op.add_column('corrections', sa.Column('gemini_doc_name', sa.String(length=500), nullable=True))
    op.add_column('corrections', sa.Column('injection_status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corrections', 'injection_status')
    op.drop_column('corrections', 'gemini_doc_name')
    op.drop_column('corrections', 'domain')
    # ### end Alembic commands ###
