"""add_conversation_id_to_chat_logs

Revision ID: 98ee2ada049e
Revises: c4d5e6f7a8b9
Create Date: 2026-03-28 22:26:45.168416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ee2ada049e'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_pages',
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=32), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('batch_file', sa.String(length=500), nullable=True),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_index(op.f('ix_scraped_pages_job_id'), 'scraped_pages', ['job_id'], unique=False)
    op.add_column('chat_logs', sa.Column('conversation_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_chat_logs_conversation_id'), 'chat_logs', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_logs_conversation_id'), table_name='chat_logs')
    op.drop_column('chat_logs', 'conversation_id')
    op.drop_index(op.f('ix_scraped_pages_job_id'), table_name='scraped_pages')
    op.drop_table('scraped_pages')
    # ### end Alembic commands ###
